### ISSUE TITLE
Add Payout Button to Payouts page

### ISSUE THREAD

**Issue by rossbulat** [paritytech/polkadot-staking-dashboard#152]
Add a button to initiate payouts if the active account is actively staking and there are pending payouts. 

The concept of manually triggering payouts may be strange to users to are accustomed to automatically receiving payouts, so we need to be careful here to communicate that validators themselves usually take the initiative to initiate payouts, but as a convenience can be used by anyone.

Some guidelines:
- Put button on Payouts page
- Have an icon (similar to yellow circle?) in SideMenu when payouts are present
- Add additional assistant item to explain the concept of initiating payouts

To really expand this component's usefulness:
- Display how many eras / time left before the payment expires.

**Comment by xlc** [comment]
Wait, so claim pending payout is not going to be supported? Check/Claim pending payout is completely broken on pjs apps and the best alternative doesn't plan to support it at all?

**Comment by rossbulat** [comment]
> Wait, so claim pending payout is not going to be supported? Check/Claim pending payout is completely broken on pjs apps and the best alternative doesn't plan to support it at all?

Ah, yes, claiming rewards is supported now on the Nominate page, this issue is stale - I'll re-open and close it as completed.

**Comment by xlc** [comment]
Thanks for pointing it out. Please forgive me to hijack this for support request, but the pending payouts doesn't seems to be working for me. Let me know if you want me to open an issue or do something else.

Address: `HTAeD1dokCVs9MwnC1q9s2a7d2kQ52TAjrxE1y5mj5MFLLA` (this is one of the staking account of Karura LKSM protocol)

I see the pending payouts is zero

<img width="174" alt="Screenshot 2023-12-12 at 11 03 54 AM" src="https://github.com/paritytech/polkadot-staking-dashboard/assets/1201310/1b21e3b2-3c1d-47ed-916b-9a07c343671f">

But in the payout page it displays some pending payouts. And from pjs apps, it found some pending payouts. (I finally got it working after I tweaked the timeout and using a local Kusama node)

<img width="1247" alt="Screenshot 2023-12-12 at 11 04 44 AM" src="https://github.com/paritytech/polkadot-staking-dashboard/assets/1201310/cbef28f2-ebf0-49de-ab09-d3bca963b090">

Also I am expecting the claim payout button in the payout page, because it is the payout page.

The graph in the payout history is confusing. Presumably it only have last 3 days data? Because it displays `10th Dec - 12th Dec`

<img width="202" alt="Screenshot 2023-12-12 at 11 06 05 AM" src="https://github.com/paritytech/polkadot-staking-dashboard/assets/1201310/ae87f83f-9f80-47a7-ae81-be443954402f">

But the graph is from `14th Oct`, and majority of the graph is no data, and that's super confusing.
