### ISSUE TITLE
Enkrpt Wallet

### ISSUE THREAD

**Issue by jljustice** [paritytech/polkadot-staking-dashboard#1579]
Recent dashboard update shows staked DOT (roughly 840) are no longer in nominated Pools. Thoughts on why this occurring? When signed into Enkypt Wallet, that doesn't update staked balance either. Thank you for any support!

**Comment by rossbulat** [comment]
Thank you for reporting. It turns out that Enkrypt is injecting its own version of `window.ethereum`, and is is breaking a `window.ethereum.request` call to determine whether Metamask Snaps are installed. I have amended the extension provider to disable Metamask Snap if Enkrypt is installed as a quick fix, and will push an update shortly.

**Comment by rossbulat** [comment]
Fixed in the latest `@polkadot-cloud/react` patch.
