### ISSUE TITLE
Add Error Boundaries 

### ISSUE THREAD

**Issue by rossbulat** [paritytech/polkadot-staking-dashboard#160]
This issue is for discussing and implementing error boundaries in the app. 

How we implement Error Boundaries will affect how the app behaves, e.g. we could wrap an ErrorBoundary around the entire app, each page, or individual cards and modals, or all of the above. 

The error interface should be able to display a reload link to reset the component state. We can investigate the technical implementations and capabilities around this flow.

- [ ] Add modal Error Boundaries
- [ ] Add page Error Boundaries
- [ ] Add assistant Error Boundary
- [ ] Add entire application Error Boundary

Partly addresses #159

**Comment by TingALin** [comment]
Abstraction:
4 Boundaries are defined in ErrorBoundaries.tsx, and use those 4 components to wrap the corresponding section
Assistant/Application Error Boundary: define the errors inside of the index file, and error boundary component outside to handle them.
Page/Modal Error Boundaries : Each page/modal defines the errors inside, and there is a common error boundary handler to describe the errors with Page/Modal XXX is down because XXX format

**Comment by TingALin** [comment]
Entire application Error Boundary: Router.tsx
Assistant Error Boundary: Assistant
Page Error Boundaries/Modal Error Boundaries: one to wrap up all the conponents error or one for each one?

**Comment by rossbulat** [comment]
> Entire application Error Boundary: Router.tsx Assistant Error Boundary: Assistant Page Error Boundaries/Modal Error Boundaries: one to wrap up all the conponents error or one for each one?

One boundary for pages and one boundary for the modal will suffice for now. Do you have commits to reference?
