### ISSUE TITLE
Hi Ross, I'm looking forward to your creation.

### ISSUE THREAD

**Issue by ccris02** [paritytech/polkadot-staking-dashboard#26]
Here are few of my issues I've seen with Polkadot.js.org that your Dashboard could address.

**Extremely slow**
I don't know about anyone else but most of the time I don't need to see all the Validator nodes out there, I just don't care about 100 Zug or p2p nodes. 
I look at performance of my Validators or the Validators I would Nominate and maybe like 40 or 50 other 1KV nodes. 
So If there was a way we could Star or select nodes we want to pull information for to save some network resources?
We could have some special Tab where we can see the performance of all nodes but that 

**Validator Performance**
- Validator node in active set rights now or not
- Validator node Para Validating or not during specific epoch/session
- Validator node in active set #of eras in the last 28/84 Eras
- Validator node AVG era point based on #of active set nodes
- Validator points (Current, Min, Max, AVG)

**Commission Changes**
- We have seen in the past people changing Commission to stay on top of the 

**Ranking Validators by Commission**
- Looking at Polkadot.js.org you will see Validators sorted by ranking, smallest commission + lowest stake = highest ranking place
- This doesn't show actual rank of the validator in the system

**Phisherman**
- There was a concept of Phisherman which was deprecated in a way. Would it be possible to use that as a Validator performance tester. In ETH mining there is a way to figure out how much hashing power each miner has It would be nice to see if Validator nodes actual have enough resources or running it on a "potato"

_You should create Google Form for RFI (request for information) to the community_
Example of questions:
- Are you looking at this Dashboard as as Validator, Nominator or Both?
- What you do like about current Dashboard?
- What you do not like about current Dashboard?
- What would you like to see on the new Dashboard?
- Any other ecosystem Dashboards to look at for ideas?

**Comment by rossbulat** [comment]
Thanks for the great insights, there are a number of things the initial implementation is touching on to address some of your concerns from current offerings, and some of which will be addressed as we iterate the functionality.

Some things that will improve validator display performance:
- batch rendering - rendering batches of a list over a period of updates as to not overwhelm DOM updates.
- batch data fetching - ability to spawn and destroy subscription batches as and when they are presented in the DOM.

Basic validator filtering will ideally be in place by MVP. These will be presented in a user-pleasing manner, inline with the rest of the app. Where metrics match among a set of validators, a randomisation of that subset will take place as to avoid biases.

Historical era points data will be used as one of these filters, that will be a Subscan API running on top of the RPC interfaces. (all non-node based APIs will be optional for users who just want to interact with the node, otherwise successful web3 initiatives like Subscan will be supported and used).

**Comment by ccris02** [comment]
Let me know if there is any UI testing or when you will get the site up and running.
