### ISSUE TITLE
Migrate to core-ui/PageRow / HideScrollable / ButtonTab

### ISSUE THREAD

**Issue by rossbulat** [paritytech/polkadot-staking-dashboard#854]
Discontinue the wrappers and button on the dashboard side and use these new ones from `core-ui`.

Please test locally and confirm they are working, then we will publish them.

TODO(TING):

- Waiting [PR](https://github.com/paritytech/polkadot-dashboard-ui/pull/81#commits-pushed-5af0760) to be merged.
- Migrate the pagetitle(including HideScrollable / ButtonTab) to the Dashboard side.

**Comment by TingALin** [comment]
Have test locally with PageRow and HideScrollable components and the fix is [here](https://github.com/paritytech/polkadot-dashboard-ui/pull/104)

When the fix is merged, I can start migrating the following components for the previous updated components in core-ui:

- Side
- Page
- HideScrollable
- PageRow
