### ISSUE TITLE
Support of nomination in the UI

### ISSUE THREAD

**Issue by pepyakin** [paritytech/polkadot-staking-dashboard#86]
In the account picker, I selected a nominator account. The UI shows the staking payouts but otherwise tries to convince me that I am not staking. For example, that's what I see on the "Recent Payouts" panel.

<img width="255" alt="Screenshot 2022-06-01 at 20 27 06" src="https://user-images.githubusercontent.com/2205845/171476244-7477e19e-be3d-42e5-a8d8-5509fc65625c.png">

It seems to me that this should be supported since nominating is a very common use case (If not the most common) for staking in the polkadot ecosystem.

**Comment by rossbulat** [comment]
It is supported. This seems to be a bug. Is your controller also imported? Are you actively nominating?

**Comment by pepyakin** [comment]
My controller is imported but my stash is not. The account is actively nominating.

**Comment by andresilva** [comment]
I have a slightly different use-case but I think it would fit in this issue as well. My stash and controller accounts are the same, and I don't have them imported, instead I have a proxy account with `NonTransfer` policy that controls my stash (and controller since they're the same). Currently the UI only shows staking rewards for the proxy account but it doesn't show the rest of the staking stats.

(btw, I only found this project today and think it's shaping up great :)

**Comment by rossbulat** [comment]
Thanks for the info. Right now your stash account needs to be the active account, and the controller is derived from it. Having only your controller is something we need to look into supporting.

**Comment by rossbulat** [comment]
> (btw, I only found this project today and think it's shaping up great :)

Thank you! 
Porxy accounts are still not supported. We're looking at them as an advanced feature which tends to put support down the to-do list. They are on the radar though!

**Comment by rossbulat** [comment]
Hi @pepyakin, I have just merged a read-only account feature. In the event you have your controller imported but not your stash, your stash will be fetched automatically and treated as a read-only account. Please let me know if all is working on your end.

**Comment by rossbulat** [comment]
Resolved in the account selection overhaul.
